apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connme
  namespace: argocd
spec:
  project: default
  source:
    path: overlay/microk8s/connme
    repoURL: https://github.com/IvanKuchin/k8s-argocd
    targetRevision: master
  destination:
    namespace: www-connme-ru
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}



